"""create initial tables

Revision ID: 7109f86968a5
Revises:
Create Date: 2026-06-28 22:31:00.675581

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7109f86968a5'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_api_key'), 'users', ['api_key'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_code', sa.String(length=32), nullable=False),
    sa.Column('long_url', sa.String(length=2048), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_permanent', sa.Boolean(), nullable=False),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('webhook_url', sa.String(length=2048), nullable=True),
    sa.Column('webhook_threshold', sa.Integer(), nullable=True),
    sa.Column('webhook_fired', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_links_expires_at'), 'links', ['expires_at'], unique=False)
    op.create_index(op.f('ix_links_short_code'), 'links', ['short_code'], unique=True)
    op.create_index(op.f('ix_links_user_id'), 'links', ['user_id'], unique=False)
    op.create_table('clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_anonymized', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('browser', sa.String(length=64), nullable=True),
    sa.Column('os', sa.String(length=64), nullable=True),
    sa.Column('device_type', sa.String(length=16), nullable=True),
    sa.Column('referrer', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clicks_link_browser', 'clicks', ['link_id', 'browser'], unique=False)
    op.create_index('ix_clicks_link_country', 'clicks', ['link_id', 'country'], unique=False)
    op.create_index('ix_clicks_link_time', 'clicks', ['link_id', 'clicked_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clicks_link_time', table_name='clicks')
    op.drop_index('ix_clicks_link_country', table_name='clicks')
    op.drop_index('ix_clicks_link_browser', table_name='clicks')
    op.drop_table('clicks')
    op.drop_index(op.f('ix_links_user_id'), table_name='links')
    op.drop_index(op.f('ix_links_short_code'), table_name='links')
    op.drop_index(op.f('ix_links_expires_at'), table_name='links')
    op.drop_table('links')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_api_key'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
